#version: '3.8'

services:
  postgres:
    container_name: restful_code_leap_db
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
