# Generated by Django 5.1.4 on 2025-01-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_career_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Career',
            new_name='Post',
        ),
    ]
