name: Codeleap Django REST API

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.12'
    - name: Install Dependencies
      run: |
        python3 -m pip3 install --upgrade pip
        pip3 install -r requirements.txt
    - name: Run Tests
      run: |
        python3 codeleap/manage.py test codeleap/api
    - name: Login docker
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build docker image
      run: docker build -t joaov1ct0r/django_py_rest_api .
    - name: Publish image
      run: docker push joaov1ct0r/django_py_rest_api
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Remove container
        run: docker rm -f django_py_rest_api
      - name: Remove all stopped containers
        run: docker container prune -f
      - name: Remove unused images
        run: docker image prune -a -f
      - name: Remove unused volumes
        run: docker volume prune -f
      - name: Pull image docker hub
        run: docker pull joaov1ct0r/django_py_rest_api:latest
      - name: Run docker container Codeleap Django REST API
        run: docker run -d -p 8000:8000 --shm-size=1g -e POSTGRES_PASSWORD='${{secrets.POSTGRES_PASSWORD}}' -e POSTGRES_USER=${{secrets.POSTGRES_USER}} -e POSTGRES_DB=${{secrets.POSTGRES_DB}} -e POSTGRES_HOST=${{secrets.POSTGRES_HOST}} -e DEBUG=${{secrets.DEBUG}} --name django_py_rest_api joaov1ct0r/django_py_rest_api